### ISSUE TITLE
[ENH] New module load process

### ISSUE THREAD

**Issue by GlebChili** [GmodNET/GmodDotNet#45]
# Description  
Right now GmodDotNet is very opinionated about module load process, especially on client: clientside modules loaded only after the specific lua event, all modules are loaded simultaneously, etc. It sets limitations on usage and inconsistent with behavior of native Garry's Mod modules.

# Solution proposal

Modules will be loaded and unloaded by name with `dotnet_load` and `dotnet_unload` Lua functions. Code signing functionality will be provided as a separate managed module.

# TODO
- [x] Implement new module load/unload functionality.

- [ ] Develop and ship an optional managed module to provide code signing functionality.

**Comment by GlebChili** [comment]
@AaronJThompson Your thoughts about this issue?

**Comment by GlebChili** [comment]
Needs issue #46 to be resolved.

**Comment by GlebChili** [comment]
Needs issue #47 to be resolved.

**Comment by AaronJThompson** [comment]
Yes, I agree, loading by name may be the best option. It would be great to have a fully-fledged Lua API that developers and servers can use to control how GmodDotNet runs and operates. Am I right in saying we have a way to manage cross-module dependencies? For instance, maybe a module is used as a library for other modules to use? Or is that all being done with NuGet?

**Comment by GlebChili** [comment]
@AaronJThompson We rely on dotnet msbuild publish target to produce module along with all its dependencies (resolved from NuGet or otherwise). Each module lives in its own AssemblyLoadContext. So modules can always bring their dependencies without worries of conflicts: types from different contexts are completely isolated. Unfortunately it also causes some limitations: if two modules depend on absolutely the same library, the same type from such library will appear as two different classes (one for each AssemblyLoadContext). This is the reason why first versions of GmodDotNet required modules to delete GmodNET.API.dll assembly from module distribution: if such assembly was present, it used to be loaded in module's corresponding context. Thus we had two different `IModule` interfaces. So, right now inter module communication can rely only on primitive types such as strings, ints, etc, and Garry's Mod Lua types (native and custom). But I think it is OK for the most use cases now. We can think about solving this issue in the 2.0.0 development cycle.

Regarding Lua API, this what I am working now in `new-load-model` branch. GmodDotNet now exposes two global Lua functions: `dotnet_load(string: module_name)` and `dotnet_unload(string: module_name)`. I can try latest nightly build of new-load-model branch and try it yourself.

**Comment by AaronJThompson** [comment]
Okay awesome.
I agree about moving module signing into a managed module, it's not great to have it in Lua and would make our API much nicer to work with, not to mention faster.

**Comment by GlebChili** [comment]
Current Lua load API was changed a bit. `dotnet_load` is now `dotnet.load` and `dotnet_unload` is `dotnet.unload`.
