### ISSUE TITLE
[ENH] Allow native dependencies to be unloaded on module unload

### ISSUE THREAD

**Issue by GlebChili** [GmodNET/GmodDotNet#57]
# Overview

Current `GmodNetModuleAssemblyLoadContext` implementation is able to unload only managed parts of GmodDotNet modules. Thus if module brings native dependencies the game process retains reference to them until its termination, which effectively means that such modules are not really hot-reloadable.

# Possible solution

Each instance of `GmodNetModuleAssemblyLoadContext` should keep track of all native libraries requested as dependencies and free their corresponding OS references with `NativeLibrary.Free`.

**Comment by AaronJThompson** [comment]
Could we potentially abstract native module loading into an API, where we use IDisposables for both managed and native libraries which can all be cleaned up in the same format when unloading

**Comment by GlebChili** [comment]
@AaronJThompson Unfortunately not. When I'm talking about native libraries here I mean usage of extern methods with `DllImport` attribute. 

By the way, if module developers want fine-grained over native libraries, they should use new [NativeLibrary](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary?view=net-5.0) class, which grants low level access and absolutely independent of `AssemblyLoadContext`.

**Comment by AaronJThompson** [comment]
I see. In that case, the original solution sounds best
