### ISSUE TITLE
[ENH] Redirect Console.Out to Game's Console

### ISSUE THREAD

**Issue by SupinePandora43** [GmodNET/GmodDotNet#62]
* Console.SetOut
- - [x] `Tier0.Msg` c# bindings
- - [x] is `Tier0.Msg` thread safe?
- - [x] test `Tier0.Msg` & Console.Write & Console.WriteLine
- - - [x] char
- - - [x] string
- - - [x] int
- - - [x] float
- - - [x] bool

#70

**Comment by GlebChili** [comment]
@SupinePandora43 Can you find original Source headers for the SDK or some kind of documentation for us?

**Comment by SupinePandora43** [comment]
https://developer.valvesoftware.com/wiki/Developer_Console_Control

**Comment by GlebChili** [comment]
@AaronJThompson What do you think?

**Comment by SupinePandora43** [comment]
now it doesn't conflict between game sides https://github.com/SupinePandora43/GmodDotNet/commit/004c6f406df3f23a23b50b58842d69b0ceb6f3db

**Comment by AaronJThompson** [comment]
Tier0 Msg can be in the core due to Console.SetOut. However, any other source SDK bindings, Tier 0 or otherwise, must go in extensions to avoid scope creep on the core.

**Comment by SupinePandora43** [comment]
ok
