### ISSUE TITLE
[ENH] GmodDotNet must not hang the game in case when it is not possible to unload module.

### ISSUE THREAD

**Issue by GlebChili** [GmodNET/GmodDotNet#67]
# Description

If it is not possible to unload module (due to remaining references in Lua context or module code still being executed somewhere) GmodDotNet will hang the game trying to force garbage collection in effectively infinite loop. This may cause bad user experience. Thus we have to introduce new behavior in such case.

# Solution 

On module unload, GmodDotNet must try to collect garbage several times (like 100) and if module's AssemlyLoadContext is still alive, inform user of a potential memory leek and continue game execution.

**Comment by SupinePandora43** [comment]
if module crashes in `IModule.Load()` it can't be unloaded

**Comment by GlebChili** [comment]
@SupinePandora43 I guess it is somewhat expected behavior, since if module is failing to be loaded in the first place, something went horribly wrong and we even shouldn't try to recover from this situation.

**Comment by SupinePandora43** [comment]
but it couldn't be loaded again

**Comment by GlebChili** [comment]
@SupinePandora43 Good point, we need to remove failed module from the modules list.

**Comment by GlebChili** [comment]
Fixed by PR #56
