### ISSUE TITLE
[ENH] Create a proper documentation

### ISSUE THREAD

**Issue by GlebChili** [GmodNET/GmodDotNet#68]
# Description

"If you wrote the code but not the documentation it doesn’t exist." - Miguel de Icaza. That's it. We must have a proper documentation.

# Solution

For now it seems like the best way to deal with a documentation is to generate a static web site directly from code using [DocFX](https://dotnet.github.io/docfx/).

**Comment by SupinePandora43** [comment]
https://docsforge.com/

**Comment by Pdzly** [comment]
Yeah because i have no clue to install that on my server 1. There is no /bin folder in the lua folder 2. I get an error that 
![image](https://user-images.githubusercontent.com/34943569/106739851-f379e680-6619-11eb-879b-51f26280f7a4.png)

**Comment by GlebChili** [comment]
@Pdzly If `bin` folder is not present, it should be created manually.

**Comment by Pdzly** [comment]
Yeah of course i created one and did everything what the tutorial said but the error is still the same i didnt pit anything in includes but there is something missing

**Comment by SupinePandora43** [comment]
> Yeah of course i created one and did everything what the tutorial said but the error is still the same i didnt pit anything in includes but there is something missing

Are you using `x86_64` branch of gmod?

**Comment by Pdzly** [comment]
Yes i think i use definitly the client beta but is there a gmod server beta branch?

**Comment by luttje** [comment]
Say I should create tutorials, do you imagine a place in the docs for that or should I create markdown for the wiki pages here on GH?

**Comment by GlebChili** [comment]
@luttje We have decided to use [DocFX](https://dotnet.github.io/docfx/) to generate documentation. Documentation sources are contained in `docfx_project` directory: https://github.com/GmodNET/GmodDotNet/tree/main/docfx_project. The preview build of docs is available at https://docs.gmodnet.xyz/ (right now only API is documented).

**Comment by luttje** [comment]
Cool, I'll create a beginner Hello World tutorial and a tutorial explaining how to use nuget packages tonight or another time this week. 
- [x] Beginners tutorial on creating a .NET Gmod Module
- [ ] Tutorial on using nuget packages in your .NET Gmod module

You can expect a PR this week

**Comment by GlebChili** [comment]
@luttje Amazing! Your contribution will be greatly appreciated! Unfortunately, I'm very busy next two weeks, so it is not likely that I will be able to react in timely manner, but we will definitely accept your work. You can also ask @SupinePandora43 questions. We also have a repo for examples: https://github.com/GmodNET/Examples. It is good idea to contribute tutorial related code there.

You are also welcome on our Discord server, so we can communicate in more effective way (there is a link in our README).

**Comment by luttje** [comment]
@GlebChili Is there some other documentation additions I can help with here? I've got some time in between work this week to write some articles.

If anyone has something they'd like to see let me know.

I'll at least work on what I see I promised a month ago 😅:
> Tutorial on using nuget packages in your .NET Gmod module

That article will basically boil down to adding this to a .csproj PropertyGroup during development
`<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`
and publishing when releasing, so that the dependent nuget dll's are included

**Comment by GlebChili** [comment]
@luttje Tutorial about on NuGet dependencies from you would be amazing! But I think we should emphasize usage of `dotnet publish` over adding `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` property. `CopyLocalLockFileAssemblies` will force MSBuild to copy deps to output dir, certainly,  but some kinds of apps may depend on `Publish` target in order to deal with some assets, like static files in ASP.NET Core apps, which, I believe, have great usage potential for Garry's Mod servers.
