### ISSUE TITLE
[ENH] Add a shortcut for pushing Lua Global Table to ILua interface

### ISSUE THREAD

**Issue by GlebChili** [GmodNET/GmodDotNet#81]
# Description
Pushing Lua Global table to the stack requires a lot of boilerplate code like `lua.PushSpecial(SPECIAL_TABLES.SPECIAL_GLOB)`. Since working with Global table is the most common operation in GmodDotNet modules, and use cases for other special Lua tables are rare, we should introduce a shortcut for pushing Global table for better developer experience and code readability.

# Possible solution
Add `ILua.PushGlobalTable()` to `GmodNET.API`.

**Comment by SupinePandora43** [comment]
What if it will be `GmodNET.API.Extras` namespace `ILua` extension?
Just to keep `ILua` clean

**Comment by GlebChili** [comment]
I think it is not an extra, but rather a very important part of GmodDotNet experience.

**Comment by SupinePandora43** [comment]
Possible code implementation:
```cs
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public void PushGlobalTable() => this.PushSpecial(SPECIAL_TABLES.SPECIAL_GLOB);
```
but i think about something like:
```cs
GlobalTable _G = new(lua);
Console.WriteLine(_G["SERVER"] as bool);
_G["print"]("message");
_G["PrintTable"](new []{1,2,3});
```

**Comment by GlebChili** [comment]
> but i think about something like:
> 
> ```cs
> GlobalTable _G = new(lua);
> Console.WriteLine(_G["SERVER"] as bool);
> _G["print"]("message");
> _G["PrintTable"](new []{1,2,3});
> ```

Using IDictionary to work with Lua tables is interesting, but naive implementation will only work for primitive types, like number and string.

**Comment by SupinePandora43** [comment]
> > but i think about something like:
> > ```cs
> > GlobalTable _G = new(lua);
> > Console.WriteLine(_G["SERVER"] as bool);
> > _G["print"]("message");
> > _G["PrintTable"](new []{1,2,3});
> > ```
> 
> Using IDictionary to work with Lua tables is interesting, but naive implementation will only work for primitive types, like number and string.

casting:
```cs
GlobalTable _G = new(lua);
GluaDelegates.print print = (GluaDelegates.print)_G["print"];
print("msg");
```
templates:
```cs
GlobalTable _G = new(lua);
GluaDelegates.print print = _G.Get<GluaDelegates.print>("print");
print("msg");
```
also templates:
```cs
GlobalTable _G = new(lua);
GluaDelegates.print print = _G.Get<GluaDelegates.print>(); // use Type.Name;
print("msg");
```
or make a class what binds whole lua api to use like:
```cs
GlobalTable _G = new(lua);
_G.print("msg");
string osname = _G.jit.os;
_G.print($"os is {osname}");
```
ILua class extension with `._G` field:
```cs
// ILua lua
lua._G.print("message");
lua._G.MsgC(new Color(0, 255, 0, 255), "message");
```
